SELECT 
  RES.RACEID,
  RES.DRIVERID,
  RES.POSITION,
  RES.LAPS,
  LAPS.LAP,
  LAPS.TIME,
  RES.FASTESTLAP,
  RES.FASTESTLAPTIME
FROM PLAYGROUND.DATATHON.RESULTS RES
JOIN PLAYGROUND.DATATHON.LAP_TIMES LAPS
  ON LAPS.RACEID = RES.RACEID
 AND LAPS.DRIVERID = RES.DRIVERID
WHERE RES.RACEID BETWEEN 1121 AND 1144
ORDER BY RES.RACEID, RES.POSITIONORDER, LAPS.LAP;